version: '3.9'
services:
  db:
    image: postgres
    container_name: poketeam_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=poketeam
    volumes:
      - pg_data:/data/postgres
    network_mode: host

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: poketeam_api
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - ./api:/app 
    environment:
      NODE_ENV: dev
      JWT_SECRET: asdfasdfadsf
      DATABASE_URL: "postgresql://docker:docker@localhost:5432/poketeam?schema=public"
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: poketeam_web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3333
      - VITE_API_POKEMON_URL=https://pokeapi.co/api/v2/
    network_mode: host

volumes:
  pg_data:
    driver: local

